---
project: lib_qadc
title: Quasi ADC using GPIO
version: 0.0.1

documentation:
  exclude_patterns_path: doc/exclude_patterns.inc
  doxygen_projects:
    xscope_fileio:
      doxyfile_path: doc/Doxyfile.inc
  pdfs:
    doc/01_device:
      pdf_title: "{{title}} - device documentation"
      pdf_filename: "{{project}}_device_doc_v{{version}}"
