---
project: lib_qadc
title: Quasi ADC using GPIO
version: 0.0.1

documentation:
  exclude_patterns_path: doc/exclude_patterns.inc
  doxygen_projects:
    xscope_fileio:
      doxyfile_path: doc/Doxyfile.inc
  pdfs:
    doc/programming_guide/qadc:
      pdf_title: "{{title}} - Programming Guide"
      pdf_filename: "{{project}}_programming_guide_v{{version}}"
